apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: harbor-admin
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: http://192.168.68.10:8090/api
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kubernetes
        envSlug: prod
        secretsPath: /harbor
        recursive: false
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: harbor-admin
      secretNamespace: harbor
      creationPolicy: Owner
      template:
        includeAllSecrets: true
