apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-admin
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: http://192.168.68.25:8090/api
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kubernetes
        envSlug: prod
        secretsPath: /observability
        recursive: false
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: security
  managedKubeSecretReferences:
    - secretName: grafana-admin
      secretNamespace: observability
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          admin-user: admin
          admin-password: "{{ .GRAFANA_ADMIN_PASSWORD.Value }}"
