apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: sonarqube-db
  namespace: sonarqube
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: http://192.168.68.10:8090/api
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kubernetes
        envSlug: prod
        secretsPath: /sonarqube
        recursive: false
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-operator-system
  managedKubeSecretReferences:
    - secretName: sonarqube-db
      secretNamespace: sonarqube
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          password: "{{ .SONARQUBE_DB_PASSWORD.Value }}"
          jdbc-password: "{{ .SONARQUBE_DB_PASSWORD.Value }}"
