apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.gitlab.io
    chart: gitlab-runner
    targetRevision: 0.79.0
    helm:
      releaseName: gitlab-runner
      values: |
        gitlabUrl: http://gitlab.lab
        rbac:
          create: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        runners:
          secret: gitlab-runner-token
          config: |
            [[runners]]
              name = "k8s-autoscaled"
              url = "http://gitlab.lab"
              executor = "kubernetes"
              [runners.kubernetes]
                namespace = "gitlab-runner"
                image = "alpine:3.21"
                cpu_request = "100m"
                memory_request = "128Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
