apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  scaleTargetRef:
    name: gitlab-runner
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.observability.svc:9090
        metricName: gitlab_runner_jobs
        threshold: "1"
        query: sum(gitlab_runner_jobs{state="running"})
